### ISSUE TITLE
Parabola has been removed?

### ISSUE THREAD

**Issue by liyuhang1997** [karibuTW/Freedif-Mirror#1]
Parabola has been removed?

**Comment by karibuTW** [comment]
Hello
Mirror is planned for an upgrade next month but we had to remove low demand projects until then.

We plan to add it back after the upgrade (more space and 10gbits connection)

Thanks

Kari
--
Sent with Tutanota



14 Feb 2024, 04:37 by ***@***.***:

**Comment by karibuTW** [comment]
The mirror is up and running again for Parabola!
