### ISSUE TITLE
post privacy policy at a static URL

### ISSUE THREAD

**Issue by eighthave** [karibuTW/Freedif-Mirror#6]
A while back, you included a privacy policy in this GitHub Project:
* https://gitlab.com/fdroid/admin/-/issues/320#note_919042475
* https://github.com/karibuTW/Freedif-Mirror/blob/main/policySG.md

It seems to have disappeared from the mirror site though:
* https://mirror.freedif.org/policySG.md

Could you post the privacy policy somewhere?

**Comment by karibuTW** [comment]
Thanks for your email and ticket. I've corrected this issue. Sorry for this.

**Comment by eighthave** [comment]
Thanks.  I just tried it in Firefox, and it is downloading the file rather than showing it.  Seems to work in Chromium fine.  I think it is because of the MIME Type of `text/markdown`.

```console
 ~ $ curl --head https://mirror.freedif.org/policySG.md
HTTP/2 200 
last-modified: Thu, 03 Oct 2024 12:29:59 GMT
accept-ranges: bytes
content-length: 1005
content-type: text/markdown
date: Thu, 03 Oct 2024 13:56:34 GMT
server: Apache/2.4.62 (Debian)

```

**Comment by karibuTW** [comment]
I confirm same issue on my side. Working well with Chrome or Edge, but Firefox is downloading the file instead...
After investigation, it seems to be on Firefox side: https://connect.mozilla.org/t5/ideas/display-markdown-files/idi-p/6000
Version 128 has corrected this. I've tested and it works now.
